### ISSUE TITLE
Service Contract Interface

### ISSUE THREAD

**Issue by ghost** [gzak/Unity.Mvc.Wcf#1]
I have WCF Services on say - 

http://localhost:1234/IMyService.svc

In your example you refer to Service Contract Interface 

```
container.RegisterWcfClientFor<IMyService>(binding, address);
```

Are you assuming that the service contract interface (IMyService) is shared ?
or
Is the interface created by the Unity.Mvc.Wcf ? (I suppose not, I didn't see it create any interface)

Please help.

**Comment by gzak** [comment]
So if I understand correctly:

You can create a service contract interface on the "server side", so to speak, meaning it is compiled as part of the server assembly (in the same project as the server implementation).

Then, in a separate client project, you add a remote reference to the server endpoint. This basically auto generates a bunch of code in the client project which you can then work against to implement the client. One of the things you can do with the remote reference in the client project is configure it to auto generate an async version of whatever service contract exists in the server project. It can do this because the server and client are totally decoupled and independent: the client is free to auto generate its own version of the interface which is fully async just based on what it sees in the remote wsdl.

If what I have above is true, then your question is orthogonal to what Unity.Mvc.Wcf provides. The premise of Unity.Mvc.Wcf is like this:

There's a project which _both_ the server and the client share, which contains the service contract interface (be at async or otherwise). On the server side, you simply implement the interface as it's defined and host it. On the client side, rather than adding a remote reference, you simply register the same shared interface in Unity with the extension method provided in Unity.Mvc.Wcf and _it_ takes care of auto generating the necessary code for you at runtime (instead of letting VS do the auto generation for you at compile time). Essentially, this package is an incompatible alternative to adding remote references to your client project--you either use one or the other.

The key difference here is that VS's built-in remote reference system requires the server to be hosted and running somewhere, whereas Unity.Mvc.Wcf does not (at least not until runtime). This makes it very easy to use different implementations for the contract depending on the use case (like swapping in mocks for unit tests). This also makes the client development process much more lightweight, since all you need is the interface and you can get to work straight away--you don't need to figure out how to host the service somewhere just so you can start coding against it (especially if you don't own it, or there are numerous remote services you need to interact with).
